// CommonJS(library), Every file is a module(by default)
// Modules - Encapsulated code(only share min)
const names = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alt-flavours')

require('./7-mind-grenade')
sayHi('Zalak')
sayHi(names.Jake)
sayHi(names.Mira) 